apiVersion: v1
kind: Secret
metadata:
  name: vfvdfvdfvfdvdfvfdvdf-secret
  namespace: vfvdfvdfvfdvdfvfdvdf
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
