apiVersion: apps/v1
kind: Deployment
metadata:
  name: vfvdfvdfvfdvdfvfdvdf-webserver
  namespace: vfvdfvdfvfdvdfvfdvdf
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vfvdfvdfvfdvdfvfdvdf-mysql-secrets
              key: rootpassword
        image: gcr.io/PROJECT123/vfvdfvdfvfdvdfvfdvdf
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pvc-sym-m
          mountPath: /var/www/upload/image
      volumes:
      - name: vfvdfvdfvfdvdfvfdvdf-pvc-sym-m
        persistentVolumeClaim:
          claimName: vfvdfvdfvfdvdfvfdvdf-pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  name: vfvdfvdfvfdvdfvfdvdf-web-service
  namespace: vfvdfvdfvfdvdfvfdvdf
  labels:
    run: vfvdfvdfvfdvdfvfdvdf-web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: apache
---
apiVersion: v1                  
kind: PersistentVolumeClaim     
metadata:                       
   name: vfvdfvdfvfdvdfvfdvdf-pvc-sym-uploud
   namespace: vfvdfvdfvfdvdfvfdvdf
spec:                           
   accessModes:                  
   - ReadWriteOnce              
   resources:                   
      requests:                 
         storage: 1Gi   
